version: '3.7'
services:
  selenium-chrome:
    container_name: selenium_chrome
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
